In [46]:
import pandas as pd
import matplotlib.pyplot as plt

In [47]:
mvps = pd.read_csv('mvps.csv')

In [48]:
mvps

,Unnamed: 0,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,...,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48,Year
0,0,1,Michael Jordan,27,CHI,77,891,960,0.928,82,...,6.0,5.5,2.7,1.0,0.539,0.312,0.851,20.3,0.321,1991
1,1,2,Magic Johnson,31,LAL,10,497,960,0.518,79,...,7.0,12.5,1.3,0.2,0.477,0.320,0.906,15.4,0.251,1991
2,2,3,David Robinson,25,SAS,6,476,960,0.496,82,...,13.0,2.5,1.5,3.9,0.552,0.143,0.762,17.0,0.264,1991
3,3,4,Charles Barkley,27,PHI,2,222,960,0.231,67,...,10.1,4.2,1.6,0.5,0.570,0.284,0.722,13.4,0.258,1991
4,4,5,Karl Malone,27,UTA,0,142,960,0.148,82,...,11.8,3.3,1.1,1.0,0.527,0.286,0.770,15.5,0.225,1991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
503,4,5,Jalen Brunson,27,NYK,0,142,990,0.143,77,...,3.6,6.7,0.9,0.2,0.479,0.401,0.847,11.2,0.198,2024
504,5,6,Jayson Tatum,25,BOS,0,86,990,0.087,74,...,8.1,4.9,1.0,0.6,0.471,0.376,0.833,10.4,0.189,2024
505,6,7,Anthony Edwards,22,MIN,0,18,990,0.018,79,...,5.4,5.1,1.3,0.5,0.461,0.357,0.836,7.5,0.130,2024
506,7,8,Domantas Sabonis,27,SAC,0,3,990,0.003,82,...,13.7,8.2,0.9,0.6,0.594,0.379,0.704,12.6,0.206,2024
507,8,9,Kevin Durant,35,PHO,0,1,990,0.001,75,...,6.6,5.0,0.9,1.2,0.523,0.413,0.856,8.3,0.142,2024

In [49]:
mvps = mvps[['Player', 'Year', "Pts Won", "Pts Max", "Share"]]

In [50]:
mvps.head()

            Player  Year  Pts Won  Pts Max  Share
0   Michael Jordan  1991      891      960  0.928
1    Magic Johnson  1991      497      960  0.518
2   David Robinson  1991      476      960  0.496
3  Charles Barkley  1991      222      960  0.231
4      Karl Malone  1991      142      960  0.148

In [51]:
players = pd.read_csv("players.csv")

In [52]:
players

,Unnamed: 0,Rk,Player,Age,Team,Pos,G,GS,MP,FG,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards,Year
0,0,1,Michael Jordan,27,CHI,SG,82,82,37.0,12.1,...,4.6,6.0,5.5,2.7,1.0,2.5,2.8,31.5,"MVP-1,DPOY-7,AS,NBA1,DEF1",1991
1,1,2,Karl Malone,27,UTA,PF,82,82,40.3,10.3,...,8.9,11.8,3.3,1.1,1.0,3.0,3.3,29.0,"MVP-5,AS,NBA1",1991
2,2,3,Bernard King,34,WSB,SF,64,64,37.5,11.1,...,3.2,5.0,4.6,0.9,0.3,4.0,2.9,28.4,"MVP-16,AS,NBA3",1991
3,3,4,Charles Barkley,27,PHI,SF,67,67,37.3,9.9,...,6.3,10.1,4.2,1.6,0.5,3.1,2.6,27.6,"MVP-4,AS,NBA1",1991
4,4,5,Patrick Ewing,28,NYK,C,81,81,38.3,10.4,...,8.8,11.2,3.0,1.0,3.2,3.6,3.5,26.6,"MVP-11,DPOY-7,AS,NBA2",1991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20238,754,569,Ron Harper Jr.,23,TOR,PF,1,0,4.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,2.0,0.0,NaN,2024
20239,755,570,Justin Jackson,28,MIN,SF,2,0,0.5,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,2024
20240,756,571,Dmytro Skapintsev,25,NYK,C,2,0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,2024
20241,757,572,Javonte Smart,24,PHI,PG,1,0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,2024
20242,758,NaN,League Average,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024

In [53]:
del players['Unnamed: 0']
del players['Rk']

In [54]:
players

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards,Year
0,Michael Jordan,27,CHI,SG,82,82,37.0,12.1,22.4,.539,...,4.6,6.0,5.5,2.7,1.0,2.5,2.8,31.5,"MVP-1,DPOY-7,AS,NBA1,DEF1",1991
1,Karl Malone,27,UTA,PF,82,82,40.3,10.3,19.6,.527,...,8.9,11.8,3.3,1.1,1.0,3.0,3.3,29.0,"MVP-5,AS,NBA1",1991
2,Bernard King,34,WSB,SF,64,64,37.5,11.1,23.6,.472,...,3.2,5.0,4.6,0.9,0.3,4.0,2.9,28.4,"MVP-16,AS,NBA3",1991
3,Charles Barkley,27,PHI,SF,67,67,37.3,9.9,17.4,.570,...,6.3,10.1,4.2,1.6,0.5,3.1,2.6,27.6,"MVP-4,AS,NBA1",1991
4,Patrick Ewing,28,NYK,C,81,81,38.3,10.4,20.3,.514,...,8.8,11.2,3.0,1.0,3.2,3.6,3.5,26.6,"MVP-11,DPOY-7,AS,NBA2",1991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20238,Ron Harper Jr.,23,TOR,PF,1,0,4.0,0.0,0.0,NaN,...,0.0,0.0,1.0,0.0,0.0,0.0,2.0,0.0,NaN,2024
20239,Justin Jackson,28,MIN,SF,2,0,0.5,0.0,0.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,2024
20240,Dmytro Skapintsev,25,NYK,C,2,0,1.0,0.0,0.5,.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,2024
20241,Javonte Smart,24,PHI,PG,1,0,1.0,0.0,0.0,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,2024
20242,League Average,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,.474,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024

In [55]:
players['Player'].head(50)

0        Michael Jordan
1           Karl Malone
2          Bernard King
3       Charles Barkley
4         Patrick Ewing
5         Michael Adams
6     Dominique Wilkins
7          Chris Mullin
8        David Robinson
9     Orlando Woolridge
10       Mitch Richmond
11         Tim Hardaway
12        Reggie Miller
13        Kevin Johnson
14       Hersey Hawkins
15        Tony Campbell
16       Brad Daugherty
17        Clyde Drexler
18         James Worthy
19      Hakeem Olajuwon
20         Ricky Pierce
21         Ricky Pierce
22         Ricky Pierce
23           Joe Dumars
24          Roy Tarpley
25         Antoine Carr
26        Charles Smith
27       Wayman Tisdale
28     Rolando Blackman
29         Tom Chambers
30         Derek Harper
31           Ron Harper
32           Larry Bird
33        Magic Johnson
34          Larry Nance
35         Reggie Lewis
36          Jeff Malone
37         Reggie Theus
38      Sherman Douglas
39      Derrick Coleman
40         Kevin McHale
41         Chuck Person
42         Harvey Grant
43        Tyrone Corbin
44       Lionel Simmons
45       Scottie Pippen
46          Kenny Smith
47       Terry Cummings
48          Otis Thorpe
49           Ken Norman
Name: Player, dtype: object

In [56]:
players['Player'] = players['Player'].str.replace("*", "", regex=False)

In [57]:
def single_row(df): 
    if df.shape[0]==1: 
        return df
    else:
        row = df [df ["Team"] == "TOT"]
        row["Team"] = df.iloc[-1,:]["Team"]
        return row

players =players.groupby(["Player", "Year"]).apply(single_row)

C:\Users\gusta\AppData\Local\Temp\ipykernel_60264\342761286.py:9: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  players =players.groupby(["Player", "Year"]).apply(single_row)

In [58]:
players.head(20)

                                 Player Age Team Pos   G  GS    MP   FG   FGA  \
Player        Year
A.C. Green    1991 182       A.C. Green  27  LAL  PF  82  21  26.4  3.1   6.6
              1992 550       A.C. Green  28  LAL  PF  82  53  35.4  4.7   9.8
              1993 1035      A.C. Green  29  LAL  PF  82  55  34.4  4.6   8.6
              1994 1465      A.C. Green  30  PHO  PF  82  55  34.5  5.7  11.3
              1995 2021      A.C. Green  31  PHO  SF  82  52  32.8  3.8   7.5
              1996 2601      A.C. Green  32  PHO  SF  82  36  25.8  2.6   5.4
              1998 3759      A.C. Green  34  DAL  PF  82  68  32.3  3.0   6.5
              1999 4377      A.C. Green  35  DAL  PF  50  35  18.5  2.2   5.1
              2000 4907      A.C. Green  36  LAL  PF  82  82  23.5  2.1   4.7
              2001 5466      A.C. Green  37  MIA  PF  82   1  17.2  1.8   4.0
A.J. Bramlett 2000 5084   A.J. Bramlett  23  CLE   C   8   0   7.6  0.5   2.6
A.J. English  1991 187     A.J. English  23  WSB  SG  70  12  20.6  3.6   8.2
              1992 593     A.J. English  24  WSB  SG  81   6  20.6  4.5  10.4
A.J. Green    2023 19294     A.J. Green  23  MIL  SG  35   1   9.9  1.5   3.6
              2024 19970     A.J. Green  24  MIL  SG  56   0  11.0  1.5   3.5
A.J. Guyton   2001 5381     A.J. Guyton  22  CHI  PG  33   8  19.1  2.4   5.8
              2002 5955     A.J. Guyton  23  CHI  PG  45   6  13.5  2.0   5.4
              2003 6669     A.J. Guyton  24  GSW  PG   2   0   4.5  0.0   2.0
A.J. Hammons  2017 15078   A.J. Hammons  24  DAL   C  22   0   7.4  0.8   1.9
A.J. Lawson   2024 20085    A.J. Lawson  23  DAL  SG  42   0   7.4  1.3   2.9

                           FG%  ...  DRB  TRB  AST  STL  BLK  TOV   PF   PTS  \
Player        Year              ...
A.C. Green    1991 182    .476  ...  3.8  6.3  0.9  0.7  0.3  1.2  1.4   9.1
              1992 550    .476  ...  5.6  9.3  1.4  1.1  0.4  1.4  1.7  13.6
              1993 1035   .537  ...  5.2  8.7  1.4  1.1  0.5  1.4  1.8  12.8
              1994 1465   .502  ...  5.8  9.2  1.7  0.9  0.5  1.2  1.7  14.7
              1995 2021   .504  ...  5.8  8.2  1.5  0.7  0.4  1.4  1.8  11.2
              1996 2601   .484  ...  4.7  6.8  0.9  0.5  0.3  1.0  1.7   7.5
              1998 3759   .453  ...  5.5  8.1  1.5  1.0  0.3  0.8  1.9   7.3
              1999 4377   .422  ...  2.9  4.6  0.5  0.6  0.2  0.4  1.4   4.9
              2000 4907   .447  ...  4.0  5.9  1.0  0.6  0.2  0.6  1.5   5.0
              2001 5466   .444  ...  2.5  3.8  0.5  0.4  0.1  0.5  1.5   4.5
A.J. Bramlett 2000 5084   .190  ...  1.3  2.8  0.0  0.1  0.0  0.4  1.6   1.0
A.J. English  1991 187    .439  ...  1.2  2.1  2.5  0.4  0.2  1.6  1.8   8.8
              1992 593    .433  ...  1.2  2.1  1.8  0.4  0.1  1.1  2.0  10.9
A.J. Green    2023 19294  .424  ...  1.1  1.3  0.6  0.2  0.0  0.3  0.9   4.4
              2024 19970  .423  ...  1.0  1.1  0.5  0.2  0.1  0.2  0.9   4.5
A.J. Guyton   2001 5381   .406  ...  0.8  1.1  1.9  0.3  0.2  0.7  1.1   6.0
              2002 5955   .361  ...  0.7  1.0  1.8  0.2  0.2  0.8  0.5   5.4
              2003 6669   .000  ...  0.0  0.0  1.0  0.5  0.0  0.5  0.0   0.0
A.J. Hammons  2017 15078  .405  ...  1.3  1.6  0.2  0.0  0.6  0.5  1.0   2.2
A.J. Lawson   2024 20085  .446  ...  0.9  1.2  0.5  0.2  0.1  0.3  0.5   3.2

                         Awards  Year
Player        Year
A.C. Green    1991 182      NaN  1991
              1992 550      NaN  1992
              1993 1035     NaN  1993
              1994 1465     NaN  1994
              1995 2021     NaN  1995
              1996 2601     NaN  1996
              1998 3759     NaN  1998
              1999 4377     NaN  1999
              2000 4907     NaN  2000
              2001 5466     NaN  2001
A.J. Bramlett 2000 5084     NaN  2000
A.J. English  1991 187      NaN  1991
              1992 593      NaN  1992
A.J. Green    2023 19294    NaN  2023
              2024 19970    NaN  2024
A.J. Guyton   2001 5381     NaN  2001
              2002 5955     NaN  2002
              2003 6669     NaN  2003
A.J. Hammons  2017 15078    NaN  2017
A.J. Lawson   2024 20085    NaN  2024

[20 rows x 31 columns]

In [59]:
players.index = players.index.droplevel()

In [60]:
players.index = players.index.droplevel()

In [61]:
players

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards,Year
182,A.C. Green,27,LAL,PF,82,21,26.4,3.1,6.6,.476,...,3.8,6.3,0.9,0.7,0.3,1.2,1.4,9.1,NaN,1991
550,A.C. Green,28,LAL,PF,82,53,35.4,4.7,9.8,.476,...,5.6,9.3,1.4,1.1,0.4,1.4,1.7,13.6,NaN,1992
1035,A.C. Green,29,LAL,PF,82,55,34.4,4.6,8.6,.537,...,5.2,8.7,1.4,1.1,0.5,1.4,1.8,12.8,NaN,1993
1465,A.C. Green,30,PHO,PF,82,55,34.5,5.7,11.3,.502,...,5.8,9.2,1.7,0.9,0.5,1.2,1.7,14.7,NaN,1994
2021,A.C. Green,31,PHO,SF,82,52,32.8,3.8,7.5,.504,...,5.8,8.2,1.5,0.7,0.4,1.4,1.8,11.2,NaN,1995
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8296,Žarko Čabarkapa,24,GSW,PF,61,0,8.3,1.1,2.9,.385,...,1.2,1.8,0.3,0.2,0.1,0.6,1.4,3.3,NaN,2006
5903,Željko Rebrača,29,DET,C,74,4,15.9,2.6,5.1,.505,...,2.8,3.9,0.5,0.4,1.0,1.1,2.6,6.9,NaN,2002
6405,Željko Rebrača,30,DET,C,30,12,16.3,2.7,4.8,.552,...,2.2,3.1,0.3,0.2,0.6,1.0,2.6,6.6,NaN,2003
7611,Željko Rebrača,32,LAC,C,58,2,16.0,2.3,4.0,.568,...,2.3,3.2,0.4,0.2,0.7,0.8,2.2,5.8,NaN,2005
8224,Željko Rebrača,33,LAC,C,29,2,14.2,1.8,3.3,.542,...,1.8,2.2,0.3,0.2,0.7,0.8,2.0,4.7,NaN,2006

In [62]:
combined = players.merge(mvps, how="outer", on=["Player", "Year"])

In [63]:
combined

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,STL,BLK,TOV,PF,PTS,Awards,Year,Pts Won,Pts Max,Share
0,A.C. Green,27,LAL,PF,82,21,26.4,3.1,6.6,.476,...,0.7,0.3,1.2,1.4,9.1,NaN,1991,NaN,NaN,NaN
1,A.C. Green,28,LAL,PF,82,53,35.4,4.7,9.8,.476,...,1.1,0.4,1.4,1.7,13.6,NaN,1992,NaN,NaN,NaN
2,A.C. Green,29,LAL,PF,82,55,34.4,4.6,8.6,.537,...,1.1,0.5,1.4,1.8,12.8,NaN,1993,NaN,NaN,NaN
3,A.C. Green,30,PHO,PF,82,55,34.5,5.7,11.3,.502,...,0.9,0.5,1.2,1.7,14.7,NaN,1994,NaN,NaN,NaN
4,A.C. Green,31,PHO,SF,82,52,32.8,3.8,7.5,.504,...,0.7,0.4,1.4,1.8,11.2,NaN,1995,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14030,Žarko Čabarkapa,24,GSW,PF,61,0,8.3,1.1,2.9,.385,...,0.2,0.1,0.6,1.4,3.3,NaN,2006,NaN,NaN,NaN
14031,Željko Rebrača,29,DET,C,74,4,15.9,2.6,5.1,.505,...,0.4,1.0,1.1,2.6,6.9,NaN,2002,NaN,NaN,NaN
14032,Željko Rebrača,30,DET,C,30,12,16.3,2.7,4.8,.552,...,0.2,0.6,1.0,2.6,6.6,NaN,2003,NaN,NaN,NaN
14033,Željko Rebrača,32,LAC,C,58,2,16.0,2.3,4.0,.568,...,0.2,0.7,0.8,2.2,5.8,NaN,2005,NaN,NaN,NaN
14034,Željko Rebrača,33,LAC,C,29,2,14.2,1.8,3.3,.542,...,0.2,0.7,0.8,2.0,4.7,NaN,2006,NaN,NaN,NaN

In [64]:
combined[combined["Pts Won"] > 0]

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,STL,BLK,TOV,PF,PTS,Awards,Year,Pts Won,Pts Max,Share
190,Al Jefferson,29,CHA,C,73,73,35.0,9.6,18.8,.509,...,0.9,1.1,1.7,2.4,21.8,"MVP-8,NBA3",2014,34.0,1250.0,0.027
328,Allen Iverson,21,PHI,PG,76,74,40.1,8.2,19.8,.416,...,2.1,0.3,4.4,3.1,23.5,"MVP-17,ROY-1",1997,1.0,1150.0,0.001
330,Allen Iverson,23,PHI,SG,48,48,41.5,9.1,22.0,.412,...,2.3,0.1,3.5,2.0,26.8,"MVP-4,NBA1",1999,319.0,1180.0,0.270
331,Allen Iverson,24,PHI,SG,70,70,40.8,10.4,24.8,.421,...,2.1,0.1,3.3,2.3,28.4,"MVP-7,AS,NBA2",2000,132.0,1210.0,0.109
332,Allen Iverson,25,PHI,SG,71,71,42.0,10.7,25.5,.420,...,2.5,0.3,3.3,2.1,31.1,"MVP-1,DPOY-11,AS,NBA1",2001,1121.0,1240.0,0.904
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13533,Vince Carter,23,TOR,SF,82,82,38.1,9.6,20.7,.465,...,1.3,1.1,2.2,3.2,25.7,"MVP-10,AS,NBA3",2000,51.0,1210.0,0.042
13534,Vince Carter,24,TOR,SF,75,75,39.7,10.2,22.1,.460,...,1.5,1.1,2.2,2.7,27.6,"MVP-11,AS,NBA2",2001,7.0,1240.0,0.006
13538,Vince Carter,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2005,3.0,1270.0,0.002
13886,Yao Ming,23,HOU,C,82,82,32.8,6.5,12.5,.522,...,0.3,1.9,2.5,3.3,17.5,"MVP-14,AS,NBA3",2004,1.0,1230.0,0.001
13891,Yao Ming,28,HOU,C,77,77,33.6,7.4,13.4,.548,...,0.4,1.9,3.0,3.3,19.7,"MVP-12,AS,NBA2",2009,1.0,1210.0,0.001

In [65]:
combined[["Pts Won", "Pts Max", "Share"]] = combined[["Pts Won", "Pts Max", "Share"]].fillna(0)

In [66]:
combined

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,STL,BLK,TOV,PF,PTS,Awards,Year,Pts Won,Pts Max,Share
0,A.C. Green,27,LAL,PF,82,21,26.4,3.1,6.6,.476,...,0.7,0.3,1.2,1.4,9.1,NaN,1991,0.0,0.0,0.0
1,A.C. Green,28,LAL,PF,82,53,35.4,4.7,9.8,.476,...,1.1,0.4,1.4,1.7,13.6,NaN,1992,0.0,0.0,0.0
2,A.C. Green,29,LAL,PF,82,55,34.4,4.6,8.6,.537,...,1.1,0.5,1.4,1.8,12.8,NaN,1993,0.0,0.0,0.0
3,A.C. Green,30,PHO,PF,82,55,34.5,5.7,11.3,.502,...,0.9,0.5,1.2,1.7,14.7,NaN,1994,0.0,0.0,0.0
4,A.C. Green,31,PHO,SF,82,52,32.8,3.8,7.5,.504,...,0.7,0.4,1.4,1.8,11.2,NaN,1995,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14030,Žarko Čabarkapa,24,GSW,PF,61,0,8.3,1.1,2.9,.385,...,0.2,0.1,0.6,1.4,3.3,NaN,2006,0.0,0.0,0.0
14031,Željko Rebrača,29,DET,C,74,4,15.9,2.6,5.1,.505,...,0.4,1.0,1.1,2.6,6.9,NaN,2002,0.0,0.0,0.0
14032,Željko Rebrača,30,DET,C,30,12,16.3,2.7,4.8,.552,...,0.2,0.6,1.0,2.6,6.6,NaN,2003,0.0,0.0,0.0
14033,Željko Rebrača,32,LAC,C,58,2,16.0,2.3,4.0,.568,...,0.2,0.7,0.8,2.2,5.8,NaN,2005,0.0,0.0,0.0
14034,Željko Rebrača,33,LAC,C,29,2,14.2,1.8,3.3,.542,...,0.2,0.7,0.8,2.0,4.7,NaN,2006,0.0,0.0,0.0

In [67]:
teams = pd.read_csv("team_stats.csv")

In [68]:
teams.head(10)

,Unnamed: 0,W,L,W/L%,GB,PS/G,PA/G,SRS,Year,Team
0,0,56,26,.683,—,111.5,105.7,5.22,1991,Boston Celtics*
1,1,44,38,.537,12.0,105.4,105.6,-0.39,1991,Philadelphia 76ers*
2,2,39,43,.476,17.0,103.1,103.3,-0.43,1991,New York Knicks*
3,3,30,52,.366,26.0,101.4,106.4,-4.84,1991,Washington Bullets
4,4,26,56,.317,30.0,102.9,107.5,-4.53,1991,New Jersey Nets
5,5,24,58,.293,32.0,101.8,107.8,-5.91,1991,Miami Heat
6,6,Central Division,Central Division,Central Division,Central Division,Central Division,Central Division,Central Division,1991,Central Division
7,7,61,21,.744,—,110.0,101.0,8.57,1991,Chicago Bulls*
8,8,50,32,.610,11.0,100.1,96.8,3.08,1991,Detroit Pistons*
9,9,48,34,.585,13.0,106.4,104.0,2.33,1991,Milwaukee Bucks*

In [69]:
teams = teams[~teams["W"].str.contains("Division")]

In [70]:
teams.head(10)

,Unnamed: 0,W,L,W/L%,GB,PS/G,PA/G,SRS,Year,Team
0,0,56,26,.683,—,111.5,105.7,5.22,1991,Boston Celtics*
1,1,44,38,.537,12.0,105.4,105.6,-0.39,1991,Philadelphia 76ers*
2,2,39,43,.476,17.0,103.1,103.3,-0.43,1991,New York Knicks*
3,3,30,52,.366,26.0,101.4,106.4,-4.84,1991,Washington Bullets
4,4,26,56,.317,30.0,102.9,107.5,-4.53,1991,New Jersey Nets
5,5,24,58,.293,32.0,101.8,107.8,-5.91,1991,Miami Heat
7,7,61,21,.744,—,110.0,101.0,8.57,1991,Chicago Bulls*
8,8,50,32,.610,11.0,100.1,96.8,3.08,1991,Detroit Pistons*
9,9,48,34,.585,13.0,106.4,104.0,2.33,1991,Milwaukee Bucks*
10,10,43,39,.524,18.0,109.8,109.0,0.72,1991,Atlanta Hawks*

In [71]:
teams.columns = teams.columns.str.strip()

In [72]:
teams["Team"] = teams["Team"].str.replace("*", "", regex=False)

In [73]:
teams

,Unnamed: 0,W,L,W/L%,GB,PS/G,PA/G,SRS,Year,Team
0,0,56,26,.683,—,111.5,105.7,5.22,1991,Boston Celtics
1,1,44,38,.537,12.0,105.4,105.6,-0.39,1991,Philadelphia 76ers
2,2,39,43,.476,17.0,103.1,103.3,-0.43,1991,New York Knicks
3,3,30,52,.366,26.0,101.4,106.4,-4.84,1991,Washington Bullets
4,4,26,56,.317,30.0,102.9,107.5,-4.53,1991,New Jersey Nets
...,...,...,...,...,...,...,...,...,...,...
1133,13,50,32,.610,—,117.9,115.6,2.30,2024,Dallas Mavericks
1134,14,49,33,.598,1.0,115.1,110.7,4.46,2024,New Orleans Pelicans
1135,15,41,41,.500,9.0,114.3,113.2,1.24,2024,Houston Rockets
1136,16,27,55,.329,23.0,105.8,112.8,-6.57,2024,Memphis Grizzlies
1137,17,22,60,.268,28.0,112.1,118.6,-5.80,2024,San Antonio Spurs

In [74]:
teams["Team"].unique()

array(['Boston Celtics', 'Philadelphia 76ers', 'New York Knicks',
       'Washington Bullets', 'New Jersey Nets', 'Miami Heat',
       'Chicago Bulls', 'Detroit Pistons', 'Milwaukee Bucks',
       'Atlanta Hawks', 'Indiana Pacers', 'Cleveland Cavaliers',
       'Charlotte Hornets', 'San Antonio Spurs', 'Utah Jazz',
       'Houston Rockets', 'Orlando Magic', 'Minnesota Timberwolves',
       'Dallas Mavericks', 'Denver Nuggets', 'Portland Trail Blazers',
       'Los Angeles Lakers', 'Phoenix Suns', 'Golden State Warriors',
       'Seattle SuperSonics', 'Los Angeles Clippers', 'Sacramento Kings',
       'Toronto Raptors', 'Vancouver Grizzlies', 'Washington Wizards',
       'Memphis Grizzlies', 'New Orleans Hornets', 'Charlotte Bobcats',
       'New Orleans/Oklahoma City Hornets', 'Oklahoma City Thunder',
       'Brooklyn Nets', 'New Orleans Pelicans'], dtype=object)

In [75]:
combined["Team"].unique()

array(['LAL', 'PHO', 'DAL', 'MIA', 'CLE', 'WSB', 'MIL', 'CHI', 'GSW',
       'IND', 'WAS', 'MIN', 'BOS', 'ATL', 'HOU', 'ORL', 'DEN', 'NOH',
       'TOR', 'CHO', 'PHI', 'POR', 'OKC', 'UTA', 'SEA', 'NJN', 'LAC',
       'CHA', 'SAC', 'NYK', 'NOP', 'BRK', 'DET', 'SAS', 'MEM', 'CHH',
       'VAN', 'NOK', nan], dtype=object)

In [76]:
nicknames = {}

with open("nicknames.csv") as f:
    lines = f.readlines()
    for line in lines[1:]:
        abbrev, name = line.replace("\n", "").split(",")
        nicknames[abbrev] = name

In [77]:
combined["Team"] = combined["Team"].map(nicknames)

In [78]:
combined.head(5)

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,STL,BLK,TOV,PF,PTS,Awards,Year,Pts Won,Pts Max,Share
0,A.C. Green,27,Los Angeles Lakers,PF,82,21,26.4,3.1,6.6,.476,...,0.7,0.3,1.2,1.4,9.1,NaN,1991,0.0,0.0,0.0
1,A.C. Green,28,Los Angeles Lakers,PF,82,53,35.4,4.7,9.8,.476,...,1.1,0.4,1.4,1.7,13.6,NaN,1992,0.0,0.0,0.0
2,A.C. Green,29,Los Angeles Lakers,PF,82,55,34.4,4.6,8.6,.537,...,1.1,0.5,1.4,1.8,12.8,NaN,1993,0.0,0.0,0.0
3,A.C. Green,30,Phoenix Suns,PF,82,55,34.5,5.7,11.3,.502,...,0.9,0.5,1.2,1.7,14.7,NaN,1994,0.0,0.0,0.0
4,A.C. Green,31,Phoenix Suns,SF,82,52,32.8,3.8,7.5,.504,...,0.7,0.4,1.4,1.8,11.2,NaN,1995,0.0,0.0,0.0

In [79]:
del combined["Awards"]

In [80]:
combined["Team"] = combined["Team"].str.strip()
teams["Team"] = teams["Team"].str.strip()

combined["Team"] = combined["Team"].str.lower()
teams["Team"] = teams["Team"].str.lower()

# Se ainda houver problemas de acentuação ou codificação:
combined["Team"] = combined["Team"].str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')
teams["Team"] = teams["Team"].str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')

In [81]:
stats = combined.merge(teams, how="inner", on=["Team", "Year"])

In [82]:
stats

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,Pts Max,Share,Unnamed: 0,W,L,W/L%,GB,PS/G,PA/G,SRS
0,A.C. Green,27,los angeles lakers,PF,82,21,26.4,3.1,6.6,.476,...,0.0,0.0,10,58,24,.707,5.0,106.3,99.6,6.73
1,A.C. Green,28,los angeles lakers,PF,82,53,35.4,4.7,9.8,.476,...,0.0,0.0,13,43,39,.524,14.0,100.4,101.5,-0.95
2,A.C. Green,29,los angeles lakers,PF,82,55,34.4,4.6,8.6,.537,...,0.0,0.0,12,39,43,.476,23.0,104.2,105.5,-1.20
3,A.C. Green,30,phoenix suns,PF,82,55,34.5,5.7,11.3,.502,...,0.0,0.0,9,56,26,.683,7.0,108.2,103.4,4.68
4,A.C. Green,31,phoenix suns,SF,82,52,32.8,3.8,7.5,.504,...,0.0,0.0,8,59,23,.720,—,110.6,106.8,3.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13972,Žarko Čabarkapa,24,golden state warriors,PF,61,0,8.3,1.1,2.9,.385,...,0.0,0.0,11,34,48,.415,20.0,98.5,99.8,-1.11
13973,Željko Rebrača,29,detroit pistons,C,74,4,15.9,2.6,5.1,.505,...,0.0,0.0,8,50,32,.610,—,94.3,92.2,1.69
13974,Željko Rebrača,30,detroit pistons,C,30,12,16.3,2.7,4.8,.552,...,0.0,0.0,8,50,32,.610,—,91.4,87.7,2.97
13975,Željko Rebrača,32,los angeles clippers,C,58,2,16.0,2.3,4.0,.568,...,0.0,0.0,9,37,45,.451,25.0,95.7,96.5,-0.47
13976,Željko Rebrača,33,los angeles clippers,C,29,2,14.2,1.8,3.3,.542,...,0.0,0.0,8,47,35,.573,7.0,97.2,95.6,1.75

In [83]:
del stats['Unnamed: 0']

In [ ]:
stats["GB"] = stats["GB"].str.replace("—", "0")

In [92]:
stats = stats.apply(pd.to_numeric, errors="ignore")

C:\Users\gusta\AppData\Local\Temp\ipykernel_60264\3865212684.py:1: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  stats = stats.apply(pd.to_numeric, errors="ignore")

In [93]:
stats.dtypes

Player      object
Age          int64
Team        object
Pos         object
G            int64
GS           int64
MP         float64
FG         float64
FGA        float64
FG%        float64
3P         float64
3PA        float64
3P%        float64
2P         float64
2PA        float64
2P%        float64
eFG%       float64
FT         float64
FTA        float64
FT%        float64
ORB        float64
DRB        float64
TRB        float64
AST        float64
STL        float64
BLK        float64
TOV        float64
PF         float64
PTS        float64
Year         int64
Pts Won    float64
Pts Max    float64
Share      float64
W            int64
L            int64
W/L%       float64
GB         float64
PS/G       float64
PA/G       float64
SRS        float64
dtype: object

In [94]:
stats.to_csv("player_mvp_stats.csv")